version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.9.1
    environment:
      - cluster.name=hive
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - "ES_JAVA_OPTS= -Xms1G -Xmx1G"
      - bootstrap.memory_lock=true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /var/lib/esdata:/usr/share/elasticsearch/data
  cortex:
    image: thehiveproject/cortex:3.1.0-1
    environment:
      - job_directory=${job_directory}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${job_directory}:${job_directory}
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
  thehive: 
    image: thehiveproject/thehive:3.5.0
    depends_on: 
      - elasticsearch 
      - cortex 
    ports: 
      - "0.0.0.0:9000:9000" 
    command: --cortex-port 9001
volumes:
  esdata: